# Generated by Django 2.0.6 on 2018-07-02 19:10

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('website_frontend', '0005_auto_20180601_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checked_out',
            new_name='CheckedOut',
        ),
        migrations.RenameModel(
            old_name='library_cards',
            new_name='LibraryCards',
        ),
    ]
